version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.2.2
    container_name: grafana
    #    volumes:
    #      - ./.data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "0"
